In [4]:
import numpy as np


In [2]:
arr1 = np.array([6,7,8,9,10])
print(arr1)

[ 6  7  8  9 10]


In [5]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [4]:
arr3 = np.array([1, 2, 3], dtype='float64')
print(arr3)

[1. 2. 3.]


In [7]:
zeros_arr = np.zeros((2, 4))
print(zeros_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
ones_arr = np.ones((2, 3))
print(ones_arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
range_arr = np.arange(0, 10, 2)  
print(range_arr)

[0 2 4 6 8]


In [11]:
range_arr = np.arange(0, 100, 5) 
print(range_arr)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [13]:
linspace_arr = np.linspace(0, 100, 5)
print(linspace_arr)

[  0.  25.  50.  75. 100.]


In [14]:
random_arr = np.random.rand(2, 2)
print(random_arr)

[[0.77642926 0.88980033]
 [0.84947451 0.60280172]]


In [16]:
random_arr = np.random.rand(2, 2) 
print(random_arr)

[[0.13955148 0.45772682]
 [0.59095834 0.51867416]]


In [17]:
print("\nShape of arr2:", arr2.shape)


Shape of arr2: (2, 3)


In [18]:
print("Data type of arr3:", arr3.dtype)

Data type of arr3: float64


In [6]:
print(arr2.shape)

(2, 3)


In [19]:
print("Number of dimensions of arr2:", arr2.ndim)

Number of dimensions of arr2: 2


In [20]:
print("Size of arr2:", arr2.size)

Size of arr2: 6


In [21]:
reshaped_arr = arr1.reshape(5, 1)
print(reshaped_arr)

[[ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [22]:
print("\nElement at index 0 of arr1:", arr1[0])
print("Element at row 1, column 2 of arr2:", arr2[1, 2])


Element at index 0 of arr1: 6
Element at row 1, column 2 of arr2: 6


In [1]:
import numpy as np

random_numbers = np.random.randint(1, 101,10)  # 101 is exclusive
print(random_numbers)

[28 32 74 56 46 65 48 99 94 31]


In [3]:
import numpy as np

bins = np.linspace(1, 100, num=11)
print(bins)

[  1.   10.9  20.8  30.7  40.6  50.5  60.4  70.3  80.2  90.1 100. ]


In [4]:
bins = np.linspace(1, 100, num=11).astype(int)  # Convert bins to integers
print("Bin edges:", bins)

Bin edges: [  1  10  20  30  40  50  60  70  80  90 100]
