# Numpy

In [3]:
import numpy as np
import pandas as pd

## 1) Create an arbitrary one dimensional array called "v".

In [2]:
v = np.array([10, 20, 30, 40, 50, 60, 70])
print(v)

[10 20 30 40 50 60 70]


## 2) Create a new array which consists of the odd indices of previously created array "v".

In [3]:
v_odd = v[1::2]   
print(v_odd)

[20 40 60]


## 3) Create a new array in backwards ordering from v.

In [4]:
v_backwards = v[::-1]
print(v_backwards)


[70 60 50 40 30 20 10]


## 5) Create a two dimensional array called "m".

In [5]:
m = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10,11,12]])
print(m)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## 6) Create a new array from m, in which the elements of each row are in reverse order.

In [6]:
m_row_reversed = m[:, ::-1]
print(m_row_reversed)


[[ 3  2  1]
 [ 6  5  4]
 [ 9  8  7]
 [12 11 10]]


## 7) Another one, where the rows are in reverse order.

In [7]:
m_rows_reversed = m[::-1, :]
print(m_rows_reversed)


[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]]


## 8) Create an array from m, where columns and rows are in reverse order.

In [8]:
m_full_reversed = m[::-1, ::-1]
print(m_full_reversed)


[[12 11 10]
 [ 9  8  7]
 [ 6  5  4]
 [ 3  2  1]]


## 9) Cut of the first and last row and the first and last column.

In [9]:
m_cut = m[1:-1, 1:-1]
print(m_cut)


[[5]
 [8]]


##  Extract from the array np.array([3,4,6,10,24,89,45,43,46,99,100]) with Boolean masking all the number
 ## • which are not divisible by 3
 ## • which are divisible by 5
## • which are divisible by 3 and 5
## • which are divisible by 3 and set them to 42

In [12]:
import numpy as np
A = np.array([3,4,6,10,24,89,45,43,46,99,100])
div3 = A[A%3!=0]
print("Elements of A not divisible by 3:")
print(div3)
div5 = A[A%5==0]
print("Elements of A divisible by 5:")
print(div5)
print("Elements of A, which are divisible by 3 and 5:")
print(A[(A%3==0) & (A%5==0)])


A[A%3==0] = 42
print("""New values of A after setting the elements of A,
which are divisible by 3, to 42:""")
print(A)

Elements of A not divisible by 3:
[  4  10  89  43  46 100]
Elements of A divisible by 5:
[ 10  45 100]
Elements of A, which are divisible by 3 and 5:
[45]
New values of A after setting the elements of A,
which are divisible by 3, to 42:
[ 42   4  42  10  42  89  42  43  46  42 100]


In [26]:
df=pd.DataFrame({'id':range(1,11)})
df["Date"]=pd.to_datetime(np.random.choice(pd.date_range("2020-01-01","2020-12-31"),size=10))
df["Job"]=np.random.choice(["enbhj","erghcc"],size=10,p=[0.7,0.3])
display(df)

id       Date     Job
0   1 2020-04-07   enbhj
1   2 2020-06-28   enbhj
2   3 2020-01-27   enbhj
3   4 2020-03-15   enbhj
4   5 2020-08-13   enbhj
5   6 2020-07-14   enbhj
6   7 2020-07-24  erghcc
7   8 2020-07-17   enbhj
8   9 2020-04-01   enbhj
9  10 2020-05-11   enbhj

In [10]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'id': range(1, 11)})

# Generate random dates directly
df['random_date'] = pd.to_datetime(
    np.random.choice(pd.date_range("2020-01-01", "2023-12-31"), size=len(df))
)

print(df)


   id random_date
0   1  2020-04-14
1   2  2021-06-29
2   3  2023-08-22
3   4  2022-11-18
4   5  2023-10-24
5   6  2023-01-23
6   7  2021-03-29
7   8  2021-09-10
8   9  2020-10-23
9  10  2022-05-18
